import { Application, ApplicationStatus } from './supabase';

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    user_id: 'mock',
    company_name: 'Stripe',
    job_title: 'Senior Frontend Engineer',
    job_url: 'https://stripe.com/jobs',
    job_description: 'Build the next generation of payment interfaces...',
    status: 'interview',
    salary_min: 180000,
    salary_max: 220000,
    location: 'San Francisco, CA',
    is_remote: true,
    notes: 'Had a great first call with the recruiter. Technical screen next week.',
    applied_date: '2026-05-10',
    interview_date: '2026-06-01T14:00:00Z',
    tags: ['React', 'TypeScript', 'Payments'],
    match_percentage: 92,
    created_at: '2026-05-10T10:00:00Z',
    updated_at: '2026-05-15T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'mock',
    company_name: 'Linear',
    job_title: 'Staff Engineer',
    job_url: 'https://linear.app/jobs',
    job_description: 'Work on Linear\'s core product and infrastructure...',
    status: 'applied',
    salary_min: 200000,
    salary_max: 250000,
    location: 'Remote',
    is_remote: true,
    notes: 'Applied via referral from a friend.',
    applied_date: '2026-05-18',
    interview_date: null,
    tags: ['TypeScript', 'React', 'Node.js'],
    match_percentage: 87,
    created_at: '2026-05-18T10:00:00Z',
    updated_at: '2026-05-18T10:00:00Z',
  },
  {
    id: '3',
    user_id: 'mock',
    company_name: 'Vercel',
    job_title: 'Frontend Engineer',
    job_url: 'https://vercel.com/careers',
    job_description: 'Join the team building the future of web development...',
    status: 'saved',
    salary_min: 160000,
    salary_max: 200000,
    location: 'Remote',
    is_remote: true,
    notes: '',
    applied_date: null,
    interview_date: null,
    tags: ['Next.js', 'React', 'TypeScript'],
    match_percentage: 95,
    created_at: '2026-05-20T10:00:00Z',
    updated_at: '2026-05-20T10:00:00Z',
  },
  {
    id: '4',
    user_id: 'mock',
    company_name: 'Notion',
    job_title: 'Product Engineer',
    job_url: 'https://notion.so/jobs',
    job_description: 'Build collaborative features for millions of users...',
    status: 'offer',
    salary_min: 190000,
    salary_max: 230000,
    location: 'New York, NY',
    is_remote: false,
    notes: 'Got the offer! Need to decide by June 5.',
    applied_date: '2026-04-28',
    interview_date: '2026-05-12T10:00:00Z',
    tags: ['React', 'TypeScript', 'Collaboration'],
    match_percentage: 89,
    created_at: '2026-04-28T10:00:00Z',
    updated_at: '2026-05-25T10:00:00Z',
  },
  {
    id: '5',
    user_id: 'mock',
    company_name: 'Figma',
    job_title: 'Software Engineer, Editor',
    job_url: 'https://figma.com/careers',
    job_description: 'Work on the core editing experience...',
    status: 'rejected',
    salary_min: 170000,
    salary_max: 210000,
    location: 'San Francisco, CA',
    is_remote: true,
    notes: 'Rejected after final round. Feedback: needed more system design experience.',
    applied_date: '2026-04-15',
    interview_date: '2026-05-01T10:00:00Z',
    tags: ['C++', 'WebAssembly', 'Graphics'],
    match_percentage: 72,
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-05-10T10:00:00Z',
  },
  {
    id: '6',
    user_id: 'mock',
    company_name: 'Anthropic',
    job_title: 'Frontend Engineer',
    job_url: 'https://anthropic.com/careers',
    job_description: 'Build interfaces for AI products...',
    status: 'saved',
    salary_min: 200000,
    salary_max: 260000,
    location: 'San Francisco, CA',
    is_remote: true,
    notes: 'Very excited about this one.',
    applied_date: null,
    interview_date: null,
    tags: ['React', 'TypeScript', 'AI'],
    match_percentage: 91,
    created_at: '2026-05-22T10:00:00Z',
    updated_at: '2026-05-22T10:00:00Z',
  },
  {
    id: '7',
    user_id: 'mock',
    company_name: 'GitHub',
    job_title: 'Senior Software Engineer',
    job_url: 'https://github.careers',
    job_description: 'Improve the developer experience for millions...',
    status: 'applied',
    salary_min: 175000,
    salary_max: 215000,
    location: 'Remote',
    is_remote: true,
    notes: 'Applied directly on website.',
    applied_date: '2026-05-19',
    interview_date: null,
    tags: ['Ruby', 'React', 'Go'],
    match_percentage: 80,
    created_at: '2026-05-19T10:00:00Z',
    updated_at: '2026-05-19T10:00:00Z',
  },
];

export const MOCK_JOBS = [
  {
    id: 'j1',
    company: 'OpenAI',
    logo: 'O',
    logoColor: 'bg-emerald-500',
    title: 'Senior Frontend Engineer',
    location: 'San Francisco, CA',
    type: 'Hybrid',
    salary: '$180k – $240k',
    salaryMin: 180000,
    salaryMax: 240000,
    posted: '2 days ago',
    matchPercentage: 94,
    skills: ['React', 'TypeScript', 'Python', 'GraphQL'],
    description: 'Join OpenAI to build the interfaces that millions of people use to interact with AI. You\'ll work on ChatGPT, the API platform, and other cutting-edge products.',
    isRemote: false,
    isNew: true,
  },
  {
    id: 'j2',
    company: 'Stripe',
    logo: 'S',
    logoColor: 'bg-blue-600',
    title: 'Staff Frontend Engineer',
    location: 'Remote',
    type: 'Remote',
    salary: '$200k – $260k',
    salaryMin: 200000,
    salaryMax: 260000,
    posted: '1 day ago',
    matchPercentage: 91,
    skills: ['React', 'TypeScript', 'Node.js', 'Payments'],
    description: 'Help shape Stripe\'s next generation of developer tools and payment interfaces. Work with world-class engineers on problems that matter.',
    isRemote: true,
    isNew: true,
  },
  {
    id: 'j3',
    company: 'Vercel',
    logo: 'V',
    logoColor: 'bg-gray-900',
    title: 'Frontend Engineer',
    location: 'Remote',
    type: 'Remote',
    salary: '$160k – $200k',
    salaryMin: 160000,
    salaryMax: 200000,
    posted: '3 days ago',
    matchPercentage: 96,
    skills: ['Next.js', 'React', 'TypeScript', 'CSS'],
    description: 'Build the platform that powers millions of web deployments. You\'ll work on the Dashboard, CLI, and developer experience.',
    isRemote: true,
    isNew: false,
  },
  {
    id: 'j4',
    company: 'Linear',
    logo: 'L',
    logoColor: 'bg-violet-600',
    title: 'Product Engineer',
    location: 'Remote',
    type: 'Remote',
    salary: '$180k – $230k',
    salaryMin: 180000,
    salaryMax: 230000,
    posted: '5 days ago',
    matchPercentage: 88,
    skills: ['TypeScript', 'React', 'GraphQL', 'Electron'],
    description: 'Work on Linear\'s core product used by thousands of engineering teams. Ship fast, have impact, and work with an exceptional team.',
    isRemote: true,
    isNew: false,
  },
  {
    id: 'j5',
    company: 'Figma',
    logo: 'F',
    logoColor: 'bg-orange-500',
    title: 'Senior Software Engineer',
    location: 'New York, NY',
    type: 'Hybrid',
    salary: '$175k – $220k',
    salaryMin: 175000,
    salaryMax: 220000,
    posted: '1 week ago',
    matchPercentage: 79,
    skills: ['TypeScript', 'React', 'WebAssembly', 'C++'],
    description: 'Build the design tools that creative teams rely on. Work on complex rendering, collaboration features, and developer APIs.',
    isRemote: false,
    isNew: false,
  },
  {
    id: 'j6',
    company: 'Notion',
    logo: 'N',
    logoColor: 'bg-gray-800',
    title: 'Frontend Engineer, Editor',
    location: 'San Francisco, CA',
    type: 'Hybrid',
    salary: '$160k – $200k',
    salaryMin: 160000,
    salaryMax: 200000,
    posted: '4 days ago',
    matchPercentage: 85,
    skills: ['React', 'TypeScript', 'ProseMirror', 'Yjs'],
    description: 'Build the best collaborative workspace. Work on Notion\'s core editor experience used by millions of teams worldwide.',
    isRemote: false,
    isNew: false,
  },
  {
    id: 'j7',
    company: 'Anthropic',
    logo: 'A',
    logoColor: 'bg-amber-600',
    title: 'Software Engineer, AI Products',
    location: 'San Francisco, CA',
    type: 'Hybrid',
    salary: '$200k – $280k',
    salaryMin: 200000,
    salaryMax: 280000,
    posted: '2 days ago',
    matchPercentage: 90,
    skills: ['Python', 'TypeScript', 'React', 'ML'],
    description: 'Help build AI products that are safe and beneficial. You\'ll work on Claude, our AI assistant, and the infrastructure that supports it.',
    isRemote: false,
    isNew: true,
  },
  {
    id: 'j8',
    company: 'GitHub',
    logo: 'G',
    logoColor: 'bg-gray-700',
    title: 'Senior Engineer, Copilot',
    location: 'Remote',
    type: 'Remote',
    salary: '$170k – $220k',
    salaryMin: 170000,
    salaryMax: 220000,
    posted: '6 days ago',
    matchPercentage: 83,
    skills: ['TypeScript', 'React', 'Go', 'AI/ML'],
    description: 'Build the future of AI-assisted software development. Work on GitHub Copilot, the most popular AI coding assistant.',
    isRemote: true,
    isNew: false,
  },
];

export const MOCK_INTERVIEW_QUESTIONS = {
  technical: [
    'Explain the difference between `useMemo` and `useCallback` in React, and when would you use each?',
    'What is the event loop in JavaScript? How does it handle async operations?',
    'Describe how you would architect a real-time collaborative editing feature.',
    'What are the trade-offs between server-side rendering, static site generation, and client-side rendering?',
    'How does React\'s reconciliation algorithm (Fiber) work? What are its benefits?',
    'Explain the concept of "lifting state up" in React and when it becomes a problem.',
    'How would you implement infinite scroll with optimal performance?',
    'What techniques do you use for debugging performance issues in a React application?',
  ],
  behavioral: [
    'Tell me about a time you had to deliver a project under tight deadlines.',
    'Describe a situation where you disagreed with a technical decision. How did you handle it?',
    'How do you prioritize tasks when everything seems urgent?',
    'Tell me about a time you mentored a junior engineer.',
    'Describe a project you\'re particularly proud of and why.',
    'How do you stay current with new technologies and best practices?',
    'Tell me about a failure or mistake and what you learned from it.',
  ],
  hr: [
    'Why are you looking for a new opportunity?',
    'What are your salary expectations?',
    'Where do you see yourself in 5 years?',
    'Why do you want to work at our company specifically?',
    'What is your preferred work style — independent or collaborative?',
    'How do you handle work-life balance?',
    'What are your greatest strengths and areas for improvement?',
  ],
};
